In [1]:
import pandas as pd

In [2]:
transactions = pd.read_csv("MML Week 2 /customer_transactions_contaminated.csv")

In [3]:
transactions.shape

(3200, 6)

In [4]:
transactions.head()

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer

In [5]:
transactions.shape

(3200, 6)

In [6]:
transactions.columns.tolist()

['CustomerID',
 'TransactionID',
 'TransactionDate',
 'Amount',
 'ProductCategory',
 'PaymentMethod']

In [7]:
transactions.dtypes

CustomerID         object
TransactionID      object
TransactionDate    object
Amount             object
ProductCategory    object
PaymentMethod      object
dtype: object

In [8]:
transactions.isnull().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             304
ProductCategory    299
PaymentMethod        0
dtype: int64

In [9]:
transactions.duplicated().sum()

185

In [10]:
transactions.describe(include="all")

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
count,3200,3200,3200,2896,2901,3200
unique,1871,3000,808,2603,5,4
top,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,7323a27e-8a82-4560-8bfd-dc0b1751a75c,2024-01-06,-100,Clothing,Debit Card
freq,7,2,13,39,598,809

In [11]:
for column in transactions.columns:
    print("\n---", column, "---")
    print(transactions[column].unique()[:20])

--- CustomerID ---
['60567026-f719-4cd6-849e-137e86d8938f'
 '4090ba85-b111-4f75-a792-c777965f5255'
 '9223891b-73ff-4d5c-b8ae-13ece82ee28b'
 '9243eebc-938f-480c-8564-16d503d250de'
 '6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f'
 '3eccdcf9-e8ce-4e44-9f62-8bef88e70672'
 '7fbc5847-a652-4fc8-a7d8-5e85d846e91b'
 '958e5c8d-48ca-42dd-bb71-a766a374233a'
 '39c6e7d2-6c4b-44c0-8961-ddc1ecbdb0c6'
 '474f9233-0616-431b-b3e9-a6feabe68abb'
 '187ec535-ad79-418a-aa08-86fd8a2becbb'
 '848f7178-b94b-4d8e-8baa-6a3886828887'
 'c3a5e86e-a74b-420e-b1e7-13bcbe6b71ac'
 '0e09f085-80ce-47c9-9fb2-e936ef0e9065'
 '28c29c18-0cbe-40ea-b218-a96430cc4409'
 '68b5a27d-980f-409d-9b64-acc242c86f8e'
 '54b3556e-e480-41a2-9dcd-7da1d91655aa'
 'decfbb11-2324-4a91-b4a4-da3011046f88'
 '5dfe3352-ee78-4510-a968-9aba1dd940a2'
 'be854a65-4191-467a-9237-60b4e088df5b']

--- TransactionID ---
['5ff75116-0a50-4d04-80fb-31e5ccbb0769'
 '2c39b9fe-ff57-4d39-9321-9f5cdf187aa1'
 'f79588dd-3db9-4ffa-97f8-7de0e64259f1'
 '401c0fc9-60df-4455-ad78-67c132f9897d'
 '2034aebc-8280-4254-a667-92bcd1c2be4f'
 '78dfb45e-16e0-4ecc-8f67-f2e210c31c3e'
 '591f1ea2-c97d-44dd-9539-71ac89b94ff3'
 'fb24e098-3ab9-40a2-bcc3-b8ebb23f549a'
 '833b026a-7c02-4101-832d-62c07569b0f6'
 'f8bde21a-7a6b-41f6-ac39-eeb77640fa9b'
 '85dc5e9e-1bd7-44e3-9a13-980736fedd3c'
 '80cd99c4-01c7-47ec-8272-79250c1c4725'
 'e101f309-f9f8-4856-aa30-0153aa5f368c'
 '65267198-f460-4051-95dc-a491fa1cab66'
 'deaec587-bd63-4556-8cea-e9d297f6651e'
 '3d5a459b-4b31-4fab-ab67-8d846e07471f'
 'c181a599-fcc7-4f9b-b618-783684e0fd24'
 '3dd5070c-5644-408f-bc17-15bf71f345a5'
 'f68315c9-1273-4ae3-8f0b-0479bc90cb5b'
 'b5d01bad-fb0a-4d50-8aa5-8f84c554096b']

--- TransactionDate ---
['2024-05-15' '2023-04-26' '2022-09-23' '2024-04-15' '2024-06-03'
 '2024-04-07' '2024-01-12' '2023-03-10' '2024-01-26' '2023-06-15'
 '2023-06-01' '2024-03-09' '2022-11-06' '2024-01-28' '2023-11-08'
 '2022-07-24' '2023-03-06' '2024-04-17' '2023-05-02' '2023-12-27']

--- Amount ---
['117.64' '466.14' '563.99' '254.44' '590.52' 'Free' nan '399.7' '296.99'
 '149.39' '255.41' '813.81' '989.99' '158.35' '140.88' '775.43' '861.39'
 '130.53' '140.01' '478.53']

--- ProductCategory ---
['Clothing' 'Health & Beauty' 'Automotive' 'Home & Garden' nan
 'Electronics']

--- PaymentMethod ---
['PayPal' 'Bank Transfer' 'Debit Card' 'Credit Card']

In [12]:
transactions["TransactionID"].duplicated().sum()

200

In [13]:
transactions[transactions["TransactionID"].duplicated(keep=False)].sort_values("TransactionID").head(20)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
3010,42d3c5b0-ec77-4567-b66c-449783077049,02221793-d5ba-4064-99d8-33c1b6722278,2023-10-03,911.51,Electronics,Credit Card
1347,42d3c5b0-ec77-4567-b66c-449783077049,02221793-d5ba-4064-99d8-33c1b6722278,2023-10-03,911.51,Electronics,Credit Card
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal
3131,9ecddfde-5bba-42c0-b4a4-8eb1b8f87c17,02747865-0adb-4e26-be16-078b8e38dcde,2022-08-30,627.83,NaN,Credit Card
2360,9ecddfde-5bba-42c0-b4a4-8eb1b8f87c17,02747865-0adb-4e26-be16-078b8e38dcde,2022-08-30,627.83,NaN,Credit Card
282,b10dbfea-ac81-4cdf-be3c-62248bbd5838,02a36fd6-8d10-4179-8b84-f011e8551a64,2024-06-02,NaN,Health & Beauty,Debit Card
3127,b10dbfea-ac81-4cdf-be3c-62248bbd5838,02a36fd6-8d10-4179-8b84-f011e8551a64,2024-06-02,NaN,Health & Beauty,Debit Card
3015,4090ba85-b111-4f75-a792-c777965f5255,04edc4fc-1565-4a82-af75-5b5caacaa9c4,2024-06-27,138.72,Home & Garden,Bank Transfer
767,4090ba85-b111-4f75-a792-c777965f5255,04edc4fc-1565-4a82-af75-5b5caacaa9c4,2024-06-27,138.72,Home & Garden,Bank Transfer
3036,e7c7f991-9b89-485f-b2e1-216ac5c661a0,06c3e20f-8aec-446a-9153-cd00a88ac1e2,2022-12-23,NaN,Clothing,Bank Transfer
671,e7c7f991-9b89-485f-b2e1-216ac5c661a0,06c3e20f-8aec-446a-9153-cd00a88ac1e2,2022-12-23,NaN,Clothing,Bank Transfer
3082,14845984-5bef-45d5-9c6a-daf55f287206,07e0737c-4e9f-4dc2-b22f-ed313498618e,2022-12-02,921.15,Home & Garden,Bank Transfer
2384,14845984-5bef-45d5-9c6a-daf55f287206,07e0737c-4e9f-4dc2-b22f-ed313498618e,2022-12-02,921.15,Home & Garden,Bank Transfer
3183,a8f82019-5586-46dc-87b2-3660e80ecd7d,09c6ac4d-2da0-4d56-8765-8c5cb8861997,2024-01-16,678.55,Clothing,Debit Card
672,a8f82019-5586-46dc-87b2-3660e80ecd7d,09c6ac4d-2da0-4d56-8765-8c5cb8861997,2024-01-16,678.55,Clothing,Debit Card
553,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,0ab4fdfb-03fe-4872-a26e-3835ed0638b7,2023-03-23,832.45,Electronics,Credit Card
3143,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,0ab4fdfb-03fe-4872-a26e-3835ed0638b7,2023-03-23,832.45,Electronics,Credit Card
3085,473f3b1f-2e0e-40a6-8917-b3aac5296a01,0b6aeade-745e-4ea7-bf67-d611199d2de8,2023-07-03,NaN,Health & Beauty,Credit Card
568,473f3b1f-2e0e-40a6-8917-b3aac5296a01,0b6aeade-745e-4ea7-bf67-d611199d2de8,2023-07-03,NaN,Health & Beauty,Credit Card

In [14]:
transactions["Amount"].value_counts(dropna=False).head(20)

Amount
NaN       304
-100       39
Free       30
0          29
185.97      3
771.33      3
717.72      3
482.63      3
37.38       2
373.37      2
627.83      2
970.59      2
168.66      2
150.03      2
911.51      2
468.05      2
978.11      2
58.43       2
244.66      2
431.64      2
Name: count, dtype: int64

In [15]:
transactions[transactions["Amount"].isin(["Free", "-100"])]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
5,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,2024-04-07,Free,NaN,Credit Card
59,04b0cd53-29ca-48ef-b4b7-9520a2939288,611876da-a85d-4969-8d84-7a9cf8ddbf59,2023-09-02,Free,Automotive,PayPal
161,56058449-276a-417e-b6c6-f8853b1d2659,b7e042d1-7ad0-430d-8984-82dfa9048a64,2024-05-29,Free,NaN,Credit Card
250,7e3256b2-49d1-419e-a30c-8504f446e64e,cd29e076-8de9-416b-bc0e-fecb61c8baff,2023-10-27,Free,Home & Garden,Credit Card
274,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,NaN,PayPal
...,...,...,...,...,...,...
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [16]:
pd.to_numeric(transactions["Amount"], errors="coerce")

0       117.64
1       466.14
2       563.99
3       254.44
4       590.52
         ...
3195    892.44
3196    431.64
3197       NaN
3198    343.46
3199       NaN
Name: Amount, Length: 3200, dtype: float64

In [17]:
amount_numeric = pd.to_numeric(transactions["Amount"], errors="coerce")

transactions[amount_numeric < 0]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,NaN,PayPal
319,b91999f9-b7ed-4da4-a285-1dafae98e21d,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100,Health & Beauty,Debit Card
334,a800ccba-e1ca-4f52-ad9f-14f3432699c9,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100,Clothing,Bank Transfer
381,a94e3f55-2f0e-432e-8706-9815c4371376,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100,Home & Garden,PayPal
447,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100,Electronics,Bank Transfer
449,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100,Home & Garden,Credit Card
476,ac6b4d61-3d14-4362-b226-8c0c5786d6df,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100,Health & Beauty,Credit Card
500,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
652,f56e56b7-bbde-455c-b570-61cd2005b4e4,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100,Automotive,PayPal
702,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100,Home & Garden,Debit Card
727,db10c135-1080-4fce-b653-d5a5fb572fa8,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100,Home & Garden,Credit Card
1129,6b6cd86a-d0af-48ab-ada5-e596f726cffa,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100,Clothing,Credit Card
1240,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100,Home & Garden,Debit Card
1241,799943c7-3b71-4f24-9b16-c2fcaf9b3871,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100,Automotive,PayPal
1263,38d746bd-c227-416a-aa28-610ffd379e58,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100,Electronics,Bank Transfer
1298,8375d38f-88e2-4c33-9647-f8b8b55b1426,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,2023-02-23,-100.0,Health & Beauty,Bank Transfer
1577,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100,Automotive,PayPal
1705,f102f93b-f32c-41d3-adcc-25e02a67c34f,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100,Electronics,PayPal
1808,28097c07-e810-4e64-8eae-bff2abd81bc1,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100,Automotive,Credit Card
1907,b7b84b81-c61b-4f23-b3db-b18010484122,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100,Clothing,PayPal
1942,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100,Electronics,PayPal
1994,d968cee0-3524-42d4-a0f7-5fe6e8284890,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100,Clothing,Debit Card
2191,1f5c50db-9c55-4bbc-8a93-c7994a7bb3d3,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100,Automotive,Bank Transfer
2239,448245da-3a0b-4f52-a40f-a25ca0a2fb6b,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100,Home & Garden,Credit Card
2319,21098ed8-fac6-4727-8f0c-953365b6c837,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100,Home & Garden,PayPal
2443,ce3f403f-b955-4364-ae22-bf351381e01f,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100,Home & Garden,Bank Transfer
2467,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100,Clothing,Debit Card
2480,eca27290-1c40-48c6-b0a5-8afedd9be099,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100,Clothing,Credit Card
2516,7e280186-770e-4c4a-b330-73dd471f956a,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100,Home & Garden,Bank Transfer
2522,bfe55c3b-668e-485d-9476-670acd50b12b,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100,Health & Beauty,Debit Card
2621,8d435ee0-fa33-4553-880a-e26511ac3921,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100,Home & Garden,Bank Transfer
2737,c56a1423-e1b0-45c1-974a-55f5fa029c88,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100,Electronics,PayPal
2910,f35c6e3f-2fac-4b7a-b713-863a0a37160c,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100,Health & Beauty,PayPal
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [18]:
transactions[amount_numeric.isna()]["Amount"].value_counts(dropna=False)

Amount
NaN     304
Free     30
Name: count, dtype: int64

In [19]:
transactions[amount_numeric < 0]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,NaN,PayPal
319,b91999f9-b7ed-4da4-a285-1dafae98e21d,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100,Health & Beauty,Debit Card
334,a800ccba-e1ca-4f52-ad9f-14f3432699c9,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100,Clothing,Bank Transfer
381,a94e3f55-2f0e-432e-8706-9815c4371376,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100,Home & Garden,PayPal
447,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100,Electronics,Bank Transfer
449,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100,Home & Garden,Credit Card
476,ac6b4d61-3d14-4362-b226-8c0c5786d6df,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100,Health & Beauty,Credit Card
500,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
652,f56e56b7-bbde-455c-b570-61cd2005b4e4,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100,Automotive,PayPal
702,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100,Home & Garden,Debit Card
727,db10c135-1080-4fce-b653-d5a5fb572fa8,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100,Home & Garden,Credit Card
1129,6b6cd86a-d0af-48ab-ada5-e596f726cffa,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100,Clothing,Credit Card
1240,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100,Home & Garden,Debit Card
1241,799943c7-3b71-4f24-9b16-c2fcaf9b3871,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100,Automotive,PayPal
1263,38d746bd-c227-416a-aa28-610ffd379e58,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100,Electronics,Bank Transfer
1298,8375d38f-88e2-4c33-9647-f8b8b55b1426,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,2023-02-23,-100.0,Health & Beauty,Bank Transfer
1577,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100,Automotive,PayPal
1705,f102f93b-f32c-41d3-adcc-25e02a67c34f,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100,Electronics,PayPal
1808,28097c07-e810-4e64-8eae-bff2abd81bc1,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100,Automotive,Credit Card
1907,b7b84b81-c61b-4f23-b3db-b18010484122,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100,Clothing,PayPal
1942,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100,Electronics,PayPal
1994,d968cee0-3524-42d4-a0f7-5fe6e8284890,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100,Clothing,Debit Card
2191,1f5c50db-9c55-4bbc-8a93-c7994a7bb3d3,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100,Automotive,Bank Transfer
2239,448245da-3a0b-4f52-a40f-a25ca0a2fb6b,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100,Home & Garden,Credit Card
2319,21098ed8-fac6-4727-8f0c-953365b6c837,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100,Home & Garden,PayPal
2443,ce3f403f-b955-4364-ae22-bf351381e01f,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100,Home & Garden,Bank Transfer
2467,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100,Clothing,Debit Card
2480,eca27290-1c40-48c6-b0a5-8afedd9be099,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100,Clothing,Credit Card
2516,7e280186-770e-4c4a-b330-73dd471f956a,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100,Home & Garden,Bank Transfer
2522,bfe55c3b-668e-485d-9476-670acd50b12b,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100,Health & Beauty,Debit Card
2621,8d435ee0-fa33-4553-880a-e26511ac3921,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100,Home & Garden,Bank Transfer
2737,c56a1423-e1b0-45c1-974a-55f5fa029c88,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100,Electronics,PayPal
2910,f35c6e3f-2fac-4b7a-b713-863a0a37160c,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100,Health & Beauty,PayPal
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [20]:
(amount_numeric < 0).sum()

40

In [21]:
transactions[amount_numeric < 0][["TransactionID", "TransactionDate", "Amount", "ProductCategory", "PaymentMethod"]]

,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,NaN,PayPal
319,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100,Health & Beauty,Debit Card
334,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100,Clothing,Bank Transfer
381,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100,Home & Garden,PayPal
447,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100,Electronics,Bank Transfer
449,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100,Home & Garden,Credit Card
476,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100,Health & Beauty,Credit Card
500,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100,Automotive,Bank Transfer
563,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
652,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100,Automotive,PayPal
702,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100,Home & Garden,Debit Card
727,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100,Home & Garden,Credit Card
1129,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100,Clothing,Credit Card
1240,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100,Home & Garden,Debit Card
1241,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100,Automotive,PayPal
1263,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100,Electronics,Bank Transfer
1298,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,2023-02-23,-100.0,Health & Beauty,Bank Transfer
1577,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100,Automotive,PayPal
1705,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100,Electronics,PayPal
1808,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100,Automotive,Credit Card
1907,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100,Clothing,PayPal
1942,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100,Electronics,PayPal
1994,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100,Clothing,Debit Card
2191,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100,Automotive,Bank Transfer
2239,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100,Home & Garden,Credit Card
2319,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100,Home & Garden,PayPal
2443,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100,Home & Garden,Bank Transfer
2467,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100,Clothing,Debit Card
2480,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100,Clothing,Credit Card
2516,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100,Home & Garden,Bank Transfer
2522,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100,Health & Beauty,Debit Card
2621,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100,Home & Garden,Bank Transfer
2737,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100,Electronics,PayPal
2910,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100,Health & Beauty,PayPal
3012,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
3038,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
3050,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
3073,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3123,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
3177,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [22]:
transactions[amount_numeric < 0]["Amount"].value_counts()

Amount
-100      39
-100.0     1
Name: count, dtype: int64

In [23]:
transactions[transactions["Amount"] == "Free"][["TransactionID", "TransactionDate", "Amount", "ProductCategory", "PaymentMethod"]]

,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
5,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,2024-04-07,Free,NaN,Credit Card
59,611876da-a85d-4969-8d84-7a9cf8ddbf59,2023-09-02,Free,Automotive,PayPal
161,b7e042d1-7ad0-430d-8984-82dfa9048a64,2024-05-29,Free,NaN,Credit Card
250,cd29e076-8de9-416b-bc0e-fecb61c8baff,2023-10-27,Free,Home & Garden,Credit Card
432,36d14454-fb95-4b19-a574-e137ddb55528,2024-02-09,Free,Electronics,Credit Card
755,a7e2384a-9efb-4519-aa01-683daa01d6e9,2024-04-14,Free,Electronics,Debit Card
764,983162b4-b06e-41d3-956c-2c3eed3cf6c4,2023-08-18,Free,Home & Garden,Debit Card
786,f9cdb10b-2e40-4df2-a7c4-3614151587b6,2024-04-11,Free,Electronics,PayPal
853,519f279a-5e5d-4a98-8a28-6c04e66c62b7,2022-09-26,Free,Electronics,PayPal
854,87459f1a-8873-450f-8b7d-ac4c7b41ba90,2023-07-20,Free,Electronics,Bank Transfer
1008,49fd3057-88b4-4896-bf5b-2e501b76df5b,2022-07-02,Free,Electronics,Credit Card
1041,8b7c550f-4acc-4333-a144-cc4d75aa8d1a,2024-01-24,Free,Home & Garden,PayPal
1179,a6ea336a-46dd-480a-9dff-232bc67e956c,2024-02-11,Free,Home & Garden,Credit Card
1214,46dbc70f-3b20-4e27-8af2-a58801d78774,2023-02-06,Free,Health & Beauty,Credit Card
1215,66f81587-2823-40f4-9f67-a51c4fb3b603,2023-09-25,Free,Clothing,Debit Card
1267,200d7d2e-ec9e-4152-865e-0e4099006397,2023-08-21,Free,Home & Garden,Debit Card
1310,8c8b85f2-5e6e-457a-899d-6c4b392d2239,2023-08-22,Free,Home & Garden,Credit Card
1460,3e221ee0-a001-4fa5-ba4e-c3ca8f381ee8,2022-07-20,Free,Home & Garden,Bank Transfer
1534,fc58b548-8913-4fb9-a952-9f6edee9d011,2023-10-07,Free,Automotive,PayPal
1748,00816003-b5ea-4564-a8f6-d25b9e44bbcf,2023-04-02,Free,Clothing,PayPal
1777,5f18cb21-0ca3-451c-ac1d-4c1dfef1a9a4,2022-07-29,Free,Clothing,Debit Card
1882,635c8590-2515-4c9b-97d9-8bfd0e909d8c,2023-10-13,Free,Electronics,Bank Transfer
2121,3044af7d-d422-474b-9b9b-687880505ffe,2023-05-09,Free,Clothing,Credit Card
2556,542e0ad1-07e0-4e9e-aa47-927c93ec08ae,2022-07-09,Free,Electronics,Bank Transfer
2608,5cb46da7-d495-45ba-8a58-23944fca1c31,2024-04-11,Free,Clothing,Credit Card
2630,cd82917c-279f-4cc0-9763-caf8589afba1,2024-02-21,Free,Clothing,Bank Transfer
2632,aa210434-2df7-48e6-acc6-c83c8cc05425,2023-01-17,Free,Health & Beauty,PayPal
2707,bbb31735-10e0-405a-8f39-c47df3cb5310,2022-12-12,Free,Clothing,PayPal
2794,de784b38-50b9-4cc0-b919-395195cae216,2022-11-08,Free,Health & Beauty,Debit Card
3005,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal

In [24]:
transactions[transactions["Amount"] == "Free"][["ProductCategory", "PaymentMethod"]].value_counts()

ProductCategory  PaymentMethod
Electronics      Bank Transfer    3
Home & Garden    Credit Card      3
Clothing         Debit Card       2
Automotive       PayPal           2
Electronics      Credit Card      2
Clothing         PayPal           2
Electronics      PayPal           2
Clothing         Credit Card      2
Home & Garden    Debit Card       2
Health & Beauty  PayPal           2
Electronics      Debit Card       1
Clothing         Bank Transfer    1
Health & Beauty  Debit Card       1
                 Credit Card      1
Home & Garden    Bank Transfer    1
                 PayPal           1
Name: count, dtype: int64

In [25]:
transactions[transactions["Amount"] == "Free"]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
5,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,2024-04-07,Free,NaN,Credit Card
59,04b0cd53-29ca-48ef-b4b7-9520a2939288,611876da-a85d-4969-8d84-7a9cf8ddbf59,2023-09-02,Free,Automotive,PayPal
161,56058449-276a-417e-b6c6-f8853b1d2659,b7e042d1-7ad0-430d-8984-82dfa9048a64,2024-05-29,Free,NaN,Credit Card
250,7e3256b2-49d1-419e-a30c-8504f446e64e,cd29e076-8de9-416b-bc0e-fecb61c8baff,2023-10-27,Free,Home & Garden,Credit Card
432,ccf4d58b-5087-45c8-a8f8-bb99be9a13d1,36d14454-fb95-4b19-a574-e137ddb55528,2024-02-09,Free,Electronics,Credit Card
755,1fbbc3ad-d48f-4e64-9ef7-4e58277af29a,a7e2384a-9efb-4519-aa01-683daa01d6e9,2024-04-14,Free,Electronics,Debit Card
764,e06f0e16-8e48-483b-b103-9f105b139ca8,983162b4-b06e-41d3-956c-2c3eed3cf6c4,2023-08-18,Free,Home & Garden,Debit Card
786,481bcc62-9dcb-4766-bbdd-79f5554d73f8,f9cdb10b-2e40-4df2-a7c4-3614151587b6,2024-04-11,Free,Electronics,PayPal
853,77280a9d-3fc9-4140-bc4e-b85cd5c7a8b1,519f279a-5e5d-4a98-8a28-6c04e66c62b7,2022-09-26,Free,Electronics,PayPal
854,68afa4cc-e2d5-4150-b358-2e14e7508721,87459f1a-8873-450f-8b7d-ac4c7b41ba90,2023-07-20,Free,Electronics,Bank Transfer
1008,8f440758-f8ac-44ee-9f83-51d9bde6d101,49fd3057-88b4-4896-bf5b-2e501b76df5b,2022-07-02,Free,Electronics,Credit Card
1041,2de49c7c-32ae-4ba8-b058-622a090d7094,8b7c550f-4acc-4333-a144-cc4d75aa8d1a,2024-01-24,Free,Home & Garden,PayPal
1179,9f9f72a5-0ec8-4847-ab9c-d7694d86f53a,a6ea336a-46dd-480a-9dff-232bc67e956c,2024-02-11,Free,Home & Garden,Credit Card
1214,13b1dad8-724d-45e8-9ecd-912d09e4931c,46dbc70f-3b20-4e27-8af2-a58801d78774,2023-02-06,Free,Health & Beauty,Credit Card
1215,4231fa1b-073c-4bf2-94d6-22dd9dd33929,66f81587-2823-40f4-9f67-a51c4fb3b603,2023-09-25,Free,Clothing,Debit Card
1267,b791d365-bf14-43ae-9939-aabd2c982866,200d7d2e-ec9e-4152-865e-0e4099006397,2023-08-21,Free,Home & Garden,Debit Card
1310,321adc94-8a35-4998-bc17-0cacc00988f4,8c8b85f2-5e6e-457a-899d-6c4b392d2239,2023-08-22,Free,Home & Garden,Credit Card
1460,ee802844-8070-4699-b60d-3568a7d306b6,3e221ee0-a001-4fa5-ba4e-c3ca8f381ee8,2022-07-20,Free,Home & Garden,Bank Transfer
1534,99462720-beca-4890-852e-79d16990f055,fc58b548-8913-4fb9-a952-9f6edee9d011,2023-10-07,Free,Automotive,PayPal
1748,69c0971b-1c85-429a-aa61-496f9c0a4410,00816003-b5ea-4564-a8f6-d25b9e44bbcf,2023-04-02,Free,Clothing,PayPal
1777,f3dc5fd3-b7ab-4996-ad89-1954cc27849e,5f18cb21-0ca3-451c-ac1d-4c1dfef1a9a4,2022-07-29,Free,Clothing,Debit Card
1882,c5dfebb9-5891-4a1d-a50c-a6851dad85cf,635c8590-2515-4c9b-97d9-8bfd0e909d8c,2023-10-13,Free,Electronics,Bank Transfer
2121,28a886bd-0c98-4532-bbb3-4ba77a9ee275,3044af7d-d422-474b-9b9b-687880505ffe,2023-05-09,Free,Clothing,Credit Card
2556,8f7a9b25-42c2-4cdd-8b0c-b66e1ca3e78a,542e0ad1-07e0-4e9e-aa47-927c93ec08ae,2022-07-09,Free,Electronics,Bank Transfer
2608,309a0ae4-8bd2-4440-935a-44f504c66431,5cb46da7-d495-45ba-8a58-23944fca1c31,2024-04-11,Free,Clothing,Credit Card
2630,32cef811-93ec-48b4-9fa5-e1174156e8cc,cd82917c-279f-4cc0-9763-caf8589afba1,2024-02-21,Free,Clothing,Bank Transfer
2632,80afb9fd-6751-40b6-b4ff-f3c08e12d4c9,aa210434-2df7-48e6-acc6-c83c8cc05425,2023-01-17,Free,Health & Beauty,PayPal
2707,a7b667f7-d6c7-4fc6-b6d9-bcdeea32297c,bbb31735-10e0-405a-8f39-c47df3cb5310,2022-12-12,Free,Clothing,PayPal
2794,7d0dffb7-45b1-456f-b4fa-512b3d1ba9ce,de784b38-50b9-4cc0-b919-395195cae216,2022-11-08,Free,Health & Beauty,Debit Card
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal

In [26]:
transactions["Amount"].value_counts(dropna=False).head(20)

Amount
NaN       304
-100       39
Free       30
0          29
185.97      3
771.33      3
717.72      3
482.63      3
37.38       2
373.37      2
627.83      2
970.59      2
168.66      2
150.03      2
911.51      2
468.05      2
978.11      2
58.43       2
244.66      2
431.64      2
Name: count, dtype: int64

In [27]:
transactions[amount_numeric < 0]["Amount"].value_counts()

Amount
-100      39
-100.0     1
Name: count, dtype: int64

In [28]:
transactions[amount_numeric < 0][["TransactionID", "TransactionDate", "Amount", "ProductCategory", "PaymentMethod"]]

,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,NaN,PayPal
319,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100,Health & Beauty,Debit Card
334,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100,Clothing,Bank Transfer
381,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100,Home & Garden,PayPal
447,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100,Electronics,Bank Transfer
449,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100,Home & Garden,Credit Card
476,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100,Health & Beauty,Credit Card
500,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100,Automotive,Bank Transfer
563,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
652,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100,Automotive,PayPal
702,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100,Home & Garden,Debit Card
727,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100,Home & Garden,Credit Card
1129,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100,Clothing,Credit Card
1240,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100,Home & Garden,Debit Card
1241,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100,Automotive,PayPal
1263,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100,Electronics,Bank Transfer
1298,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,2023-02-23,-100.0,Health & Beauty,Bank Transfer
1577,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100,Automotive,PayPal
1705,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100,Electronics,PayPal
1808,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100,Automotive,Credit Card
1907,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100,Clothing,PayPal
1942,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100,Electronics,PayPal
1994,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100,Clothing,Debit Card
2191,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100,Automotive,Bank Transfer
2239,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100,Home & Garden,Credit Card
2319,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100,Home & Garden,PayPal
2443,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100,Home & Garden,Bank Transfer
2467,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100,Clothing,Debit Card
2480,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100,Clothing,Credit Card
2516,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100,Home & Garden,Bank Transfer
2522,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100,Health & Beauty,Debit Card
2621,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100,Home & Garden,Bank Transfer
2737,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100,Electronics,PayPal
2910,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100,Health & Beauty,PayPal
3012,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
3038,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
3050,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
3073,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3123,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
3177,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [29]:
transactions[amount_numeric == 0][["TransactionID", "TransactionDate", "Amount", "ProductCategory", "PaymentMethod"]]

,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
134,793af848-8138-40e7-929c-67254ea56ca7,2023-07-22,0,Home & Garden,PayPal
196,a6b7182d-6c74-4fa5-9491-035e49e5eb87,2023-11-09,0,Electronics,Bank Transfer
308,c0ea759c-a09f-4989-bc3b-f56a0c0400d8,2022-08-13,0,Home & Garden,PayPal
378,962df48f-faf1-4849-9779-0415f10cb9f3,2023-02-08,0,Home & Garden,Credit Card
468,8e88d564-a18a-448b-9e5d-add5fef8017d,2024-05-22,0,Health & Beauty,PayPal
542,36db923e-7db3-4df0-b9c2-574410d62bba,2023-09-17,0,Electronics,Bank Transfer
580,88b6ba3b-5490-4374-ad90-cd45b1c94d4b,2023-12-31,0,Clothing,Debit Card
591,0525dc48-b90b-4100-952a-fb163c51901c,2022-11-12,0,Automotive,Debit Card
629,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,0,Electronics,Debit Card
931,35edcb11-2d5e-48ba-a1c2-8c16bbd3952a,2023-08-31,0,Clothing,Credit Card
1116,4044222b-4470-4e79-8f53-5bdba7066c44,2023-05-28,0,Electronics,PayPal
1228,721db31f-2972-4ff5-af51-87c8bb6360a3,2023-02-10,0,Clothing,Debit Card
1484,b6d45beb-65a6-468e-a9d2-9d29deaff58d,2022-09-07,0,Automotive,Debit Card
1853,e31033dc-6e31-479f-bb56-e3e392b128d5,2023-09-16,0,Home & Garden,Debit Card
1886,30bb2661-984e-4949-b821-923d76483d82,2023-10-14,0,Automotive,Debit Card
2056,71b15f40-92c8-4acd-8c45-4a6f86e11665,2023-06-21,0.0,Clothing,Credit Card
2070,4281591f-d839-4c2a-aea2-5cec07eee005,2023-04-06,0,Health & Beauty,PayPal
2109,2532b466-9d3e-4724-a5f4-b3295b4b8530,2022-11-01,0,Health & Beauty,PayPal
2166,287c98cd-4c3c-4c01-bc3f-fd2cdfb01d78,2022-11-17,0,Clothing,PayPal
2256,b302b5d0-a182-48cd-bc3c-6afbbf4c72c2,2023-04-17,0,Health & Beauty,Bank Transfer
2348,83ef29d9-c82a-4138-b8c5-599af75c3d35,2024-01-08,0,Automotive,Credit Card
2528,af93165e-0c42-4c91-bb29-a09ad16f0dab,2024-01-25,0,NaN,Debit Card
2634,d16c6727-c72f-463e-af55-0008ae1d6975,05/11/2023,0,Home & Garden,Credit Card
2662,44750adc-cb9d-4afe-a028-ffeb07e0fbcb,2023-06-08,0,Health & Beauty,Debit Card
2712,e896f88a-9035-4f79-9b7b-ba65b0fd5285,2022-08-31,0,Clothing,Credit Card
2726,3fb495d6-17d8-4d06-a679-fc0cf1b8bca3,2022-11-29,0,Automotive,Credit Card
2727,29ba8b6d-c22c-4335-b621-250d38b06acf,2023-06-29,0,Home & Garden,Debit Card
2915,b0cd6206-3611-4b1b-b4fd-eed3849cc6bd,2024-03-24,0,Health & Beauty,PayPal
2994,2d2b7edf-d53d-41e4-bd8b-b7a546002e95,2022-07-09,0,Home & Garden,Bank Transfer
3174,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal

In [30]:
transactions[amount_numeric == 0]["Amount"].value_counts(dropna=False)

Amount
0      29
0.0     1
Name: count, dtype: int64

In [31]:
len(transactions)

3200

In [32]:
(amount_numeric > 0).sum()

2796

In [33]:
transactions["Amount_Clean"] = amount_numeric

In [34]:
transactions[["Amount", "Amount_Clean"]].head(10)

   Amount  Amount_Clean
0  117.64        117.64
1  466.14        466.14
2  563.99        563.99
3  254.44        254.44
4  590.52        590.52
5    Free           NaN
6     NaN           NaN
7   399.7        399.70
8  296.99        296.99
9  149.39        149.39

In [35]:
transactions["Amount_Clean"].describe()

count    2866.000000
mean      490.916479
std       298.737439
min      -100.000000
25%       228.240000
50%       497.285000
75%       746.935000
max       999.860000
Name: Amount_Clean, dtype: float64

In [36]:
transactions[transactions["Amount"].isna()][
    ["TransactionID", "TransactionDate", "ProductCategory", "PaymentMethod"]
].head(20)

,TransactionID,TransactionDate,ProductCategory,PaymentMethod
6,591f1ea2-c97d-44dd-9539-71ac89b94ff3,2024-01-12,Automotive,PayPal
42,1e562ead-eac1-4013-87e2-2449249e49dd,2022-10-31,Electronics,Bank Transfer
48,fde080f4-b08d-4920-b29e-b7223c2aa907,2022-09-08,Health & Beauty,Bank Transfer
52,3db167d5-18aa-4073-a3fe-fb8971d83c6a,2023-08-20,NaN,Bank Transfer
60,da7bfa64-3e05-4fe0-9505-1dee627bdb3d,2022-11-30,Health & Beauty,Credit Card
61,1ca5bb66-ab5f-4832-8f31-885cd5a161a8,2024-06-09,Clothing,Credit Card
76,6f3a078b-f043-4552-9805-23bcb9083321,2023-04-20,Health & Beauty,Credit Card
77,890c8b92-5b0c-444f-b1ee-8f32cc8650b1,2023-01-22,Health & Beauty,Credit Card
83,1148f4f7-a824-4634-9b7d-9daeaedf6c17,2024-06-21,Home & Garden,Bank Transfer
106,22da76bb-b240-4e90-8efe-de5e07061c51,26/10/2022,Home & Garden,Bank Transfer
120,523497aa-0b28-45b9-9b77-3211eb35d3e9,2024-03-26,Automotive,PayPal
136,966703bc-1ed1-44f3-a868-d2f09973e857,2022-08-31,Home & Garden,Bank Transfer
138,1222182c-0888-481d-a359-892a3cd1c213,2023-05-27,Home & Garden,Bank Transfer
142,bd8b94c5-7727-45c4-95c8-ef25e79f3bb6,2024-04-29,Clothing,Bank Transfer
153,130a17e9-b485-4f32-88ca-b3a7dd8dbf55,2024-03-12,Health & Beauty,Debit Card
173,22395664-72ba-4b39-a747-181824d60836,2022-11-18,Electronics,Credit Card
212,d356ccf3-aa96-483f-acd6-f5209c71c2e0,2023-04-04,Health & Beauty,Credit Card
213,457192c9-ca74-4734-823a-41b5fe503d0b,2024-02-15,Clothing,PayPal
214,f3d57663-c4da-458e-b4f7-54eeeab859bf,2024-06-22,Home & Garden,Credit Card
218,97f0f226-6531-4acb-b5fc-a3bbcb591c17,2023-01-06,Health & Beauty,PayPal

In [37]:
transactions[transactions["Amount"].isna()]["ProductCategory"].value_counts()

ProductCategory
Health & Beauty    65
Electronics        58
Clothing           55
Automotive         52
Home & Garden      47
Name: count, dtype: int64

In [38]:
transactions["Amount"].isna().sum()

304

In [39]:
transactions[
    transactions["Amount"].isna() &
    transactions["ProductCategory"].isna()
][["TransactionID", "TransactionDate", "Amount", "ProductCategory", "PaymentMethod"]]

,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
52,3db167d5-18aa-4073-a3fe-fb8971d83c6a,2023-08-20,NaN,NaN,Bank Transfer
254,912daa90-8efc-486c-a4ce-e5f2407940ba,2022-10-13,NaN,NaN,PayPal
262,cf040478-b79e-4c3f-91ba-f6f40491edc1,2023-11-07,NaN,NaN,Bank Transfer
453,55e69849-389b-4cb8-8473-3434d70318e7,2023-05-02,NaN,NaN,Debit Card
704,9da76e9d-3804-49f0-96b4-056217265890,2024-05-28,NaN,NaN,Bank Transfer
837,bad309a4-afe9-450d-bcc5-0155b2ce7d1c,2023-03-25,NaN,NaN,Debit Card
993,27f22f16-463b-415f-8e5c-09db81e2c468,2023-05-19,NaN,NaN,Debit Card
1102,c5fe314d-d0ea-42b2-923e-36d9a0d44595,2022-10-13,NaN,NaN,Debit Card
1178,28fe80d5-0425-4952-a3a8-2d3973240b87,2023-03-23,NaN,NaN,Bank Transfer
1199,a2cbe1bb-22d9-4c68-acff-e9891048873c,2024-03-09,NaN,NaN,PayPal
1227,bfab64ba-ea96-4d36-964a-7d1416a52f64,2023-12-15,NaN,NaN,PayPal
1308,be1dbbf5-ef73-4d2f-a4ac-7745a8ce62d6,2022-09-04,NaN,NaN,Bank Transfer
1363,7b67fccd-0a58-4de3-a567-44d1c907c677,2023-03-10,NaN,NaN,PayPal
1701,4662112b-36ea-4f6d-84d2-365dd6605280,2024-03-08,NaN,NaN,PayPal
1782,c8865a23-9c7c-4210-ba71-e224f5d128ca,2022-11-25,NaN,NaN,Debit Card
2029,1c2f49aa-1e1c-4ada-b021-699f68190652,2023-10-19,NaN,NaN,PayPal
2041,29784dd5-1bda-4978-a38c-b6d462072211,2023-04-08,NaN,NaN,Credit Card
2160,38b62386-5783-4520-8633-80787f1f5173,2023-09-09,NaN,NaN,Bank Transfer
2237,1e9ca466-bb1c-4c89-a316-2ec951a72545,2023-05-03,NaN,NaN,Credit Card
2313,c6afc640-8f7d-4b89-917f-36956fcce576,2023-12-20,NaN,NaN,Bank Transfer
2374,71545c6d-1808-4ef7-89ad-be6b387b180f,2024-05-06,NaN,NaN,PayPal
2448,240cce17-e93f-4ad2-bee0-12a5545053e5,2024-04-04,NaN,NaN,PayPal
2492,fd709794-8a12-4217-b2af-4113b123b088,2024-05-26,NaN,NaN,Credit Card
2640,d4c76f11-434d-4eeb-a845-d41a7e1bc077,2024-02-26,NaN,NaN,PayPal
2797,eed391dd-9805-4afd-99d9-cc3dd538fb7f,2024-03-22,NaN,NaN,Debit Card
2881,e2273516-8218-40e5-bf53-2754a6a5e980,2024-03-09,NaN,NaN,Credit Card
3190,1c2f49aa-1e1c-4ada-b021-699f68190652,2023-10-19,NaN,NaN,PayPal

In [40]:
transactions[
    transactions["Amount"].isna() &
    transactions["ProductCategory"].isna()
]["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
PayPal           10
Bank Transfer     7
Debit Card        6
Credit Card       4
Name: count, dtype: int64

In [41]:
transactions[transactions["Amount"].isna()]["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Debit Card       80
Bank Transfer    77
Credit Card      74
PayPal           73
Name: count, dtype: int64

In [42]:
transactions["Amount_Clean"].isna().sum()

334

In [43]:
transactions.isna().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             304
ProductCategory    299
PaymentMethod        0
Amount_Clean       334
dtype: int64

In [44]:
pd.crosstab(
    transactions["Amount"].isna(),
    transactions["ProductCategory"].isna()
)

ProductCategory  False  True
Amount
False             2624    272
True               277     27

In [45]:
transactions["ProductCategory"].value_counts(dropna=False)

ProductCategory
Clothing           598
Electronics        595
Automotive         576
Health & Beauty    570
Home & Garden      562
NaN                299
Name: count, dtype: int64

In [46]:
transactions["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Debit Card       809
Credit Card      804
PayPal           794
Bank Transfer    793
Name: count, dtype: int64

In [47]:
transactions.duplicated().sum()

185

In [48]:
transactions.dtypes

CustomerID          object
TransactionID       object
TransactionDate     object
Amount              object
ProductCategory     object
PaymentMethod       object
Amount_Clean       float64
dtype: object

In [49]:
transactions_clean = transactions.drop_duplicates().copy()

In [50]:
transactions_clean.shape

(3015, 7)

In [51]:
transactions_clean["TransactionDate"] = pd.to_datetime(
    transactions_clean["TransactionDate"],
    errors="coerce"
)

In [52]:
transactions_clean["TransactionDate"].dtype

dtype('<M8[ns]')

In [53]:
transactions_clean["Amount_Clean"].isna().sum()

313

In [54]:
transactions_clean["Amount_Clean"].describe()

count    2702.000000
mean      489.788919
std       299.239453
min      -100.000000
25%       228.240000
50%       496.625000
75%       746.697500
max       999.860000
Name: Amount_Clean, dtype: float64

In [55]:
transactions_clean.dtypes

CustomerID                 object
TransactionID              object
TransactionDate    datetime64[ns]
Amount                     object
ProductCategory            object
PaymentMethod              object
Amount_Clean              float64
dtype: object

In [56]:
transactions_clean.duplicated().sum()

0

In [57]:
transactions_clean.isna().sum()

CustomerID           0
TransactionID        0
TransactionDate     98
Amount             283
ProductCategory    282
PaymentMethod        0
Amount_Clean       313
dtype: int64

In [58]:
transactions_clean.shape

(3015, 7)

In [59]:
transactions_clean[transactions_clean["TransactionDate"].isna()][
    ["TransactionID", "TransactionDate"]
].head(20)

                            TransactionID TransactionDate
31   434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e             NaT
94   05d6d53f-92d1-4be7-9346-2d142470f849             NaT
106  22da76bb-b240-4e90-8efe-de5e07061c51             NaT
121  fb09f753-0b5d-4612-9d6a-3fe220f0f3aa             NaT
124  c5c4ab32-3a2a-4748-96b7-f5ebbba384f2             NaT
238  e3a950b7-a993-4b3e-ac84-20d3e292833a             NaT
252  04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3             NaT
258  81ecc5aa-a0e6-4aab-a600-cc7137bc16a1             NaT
356  ea7f4d30-45c8-4e24-8f37-c30527a1d6a3             NaT
389  a9272080-cc7f-4f82-9977-857549f2c895             NaT
402  dc1ba702-8720-4582-9749-5bd14b886420             NaT
431  27fb25aa-f148-423f-967c-4d1764e26b29             NaT
437  f078102e-7e35-4371-b48e-2989ff4cec4f             NaT
469  0aba7275-6bd4-404d-894a-cf695bcc2b67             NaT
506  a42657eb-b99d-4b66-b0e7-96a9cd6def89             NaT
531  34d137e4-b03b-4ad4-8fc4-b1d964d5cc26             NaT
563  f39c8b1d-595a-4656-8108-25981bf3fa14             NaT
606  64f3ee25-c285-41ee-92b6-f70b006554ae             NaT
626  65520cc1-c798-4024-9caf-e1f893ef9cac             NaT
668  952adac7-c15e-47f0-ad86-aeb2205bea77             NaT

In [60]:
transactions_clean.loc[
    transactions_clean["TransactionDate"].isna(),
    "TransactionID"
].head(20)

31     434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e
94     05d6d53f-92d1-4be7-9346-2d142470f849
106    22da76bb-b240-4e90-8efe-de5e07061c51
121    fb09f753-0b5d-4612-9d6a-3fe220f0f3aa
124    c5c4ab32-3a2a-4748-96b7-f5ebbba384f2
238    e3a950b7-a993-4b3e-ac84-20d3e292833a
252    04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3
258    81ecc5aa-a0e6-4aab-a600-cc7137bc16a1
356    ea7f4d30-45c8-4e24-8f37-c30527a1d6a3
389    a9272080-cc7f-4f82-9977-857549f2c895
402    dc1ba702-8720-4582-9749-5bd14b886420
431    27fb25aa-f148-423f-967c-4d1764e26b29
437    f078102e-7e35-4371-b48e-2989ff4cec4f
469    0aba7275-6bd4-404d-894a-cf695bcc2b67
506    a42657eb-b99d-4b66-b0e7-96a9cd6def89
531    34d137e4-b03b-4ad4-8fc4-b1d964d5cc26
563    f39c8b1d-595a-4656-8108-25981bf3fa14
606    64f3ee25-c285-41ee-92b6-f70b006554ae
626    65520cc1-c798-4024-9caf-e1f893ef9cac
668    952adac7-c15e-47f0-ad86-aeb2205bea77
Name: TransactionID, dtype: object

In [61]:
transactions[
    transactions["TransactionID"].isin(
        transactions_clean.loc[
            transactions_clean["TransactionDate"].isna(),
            "TransactionID"
        ]
    )
][["TransactionID", "TransactionDate"]].head(20)

                            TransactionID TransactionDate
31   434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e      01/04/2024
94   05d6d53f-92d1-4be7-9346-2d142470f849      13/12/2022
106  22da76bb-b240-4e90-8efe-de5e07061c51      26/10/2022
121  fb09f753-0b5d-4612-9d6a-3fe220f0f3aa      25/02/2023
124  c5c4ab32-3a2a-4748-96b7-f5ebbba384f2      23/03/2023
238  e3a950b7-a993-4b3e-ac84-20d3e292833a      24/05/2023
252  04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3      16/09/2023
258  81ecc5aa-a0e6-4aab-a600-cc7137bc16a1      11/09/2023
283  7202af3a-448f-4970-9674-40f736cfdfde      2023-02-26
356  ea7f4d30-45c8-4e24-8f37-c30527a1d6a3      28/10/2022
389  a9272080-cc7f-4f82-9977-857549f2c895      12/10/2023
402  dc1ba702-8720-4582-9749-5bd14b886420      13/04/2023
431  27fb25aa-f148-423f-967c-4d1764e26b29      30/07/2022
437  f078102e-7e35-4371-b48e-2989ff4cec4f      29/12/2023
469  0aba7275-6bd4-404d-894a-cf695bcc2b67      04/03/2023
506  a42657eb-b99d-4b66-b0e7-96a9cd6def89      06/07/2022
531  34d137e4-b03b-4ad4-8fc4-b1d964d5cc26      12/07/2023
563  f39c8b1d-595a-4656-8108-25981bf3fa14      03/04/2023
606  64f3ee25-c285-41ee-92b6-f70b006554ae      12/06/2024
626  65520cc1-c798-4024-9caf-e1f893ef9cac      18/11/2022

In [62]:
transactions_clean["TransactionDate"] = pd.to_datetime(
    transactions_clean["TransactionDate"],
    dayfirst=True,
    errors="coerce"
)

In [63]:
transactions_clean["TransactionDate"].isna().sum()

98

In [64]:
transactions[
    transactions["TransactionID"].isin(
        transactions_clean.loc[
            transactions_clean["TransactionDate"].isna(),
            "TransactionID"
        ]
    )
][["TransactionID", "TransactionDate"]].head(30)

                            TransactionID TransactionDate
31   434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e      01/04/2024
94   05d6d53f-92d1-4be7-9346-2d142470f849      13/12/2022
106  22da76bb-b240-4e90-8efe-de5e07061c51      26/10/2022
121  fb09f753-0b5d-4612-9d6a-3fe220f0f3aa      25/02/2023
124  c5c4ab32-3a2a-4748-96b7-f5ebbba384f2      23/03/2023
238  e3a950b7-a993-4b3e-ac84-20d3e292833a      24/05/2023
252  04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3      16/09/2023
258  81ecc5aa-a0e6-4aab-a600-cc7137bc16a1      11/09/2023
283  7202af3a-448f-4970-9674-40f736cfdfde      2023-02-26
356  ea7f4d30-45c8-4e24-8f37-c30527a1d6a3      28/10/2022
389  a9272080-cc7f-4f82-9977-857549f2c895      12/10/2023
402  dc1ba702-8720-4582-9749-5bd14b886420      13/04/2023
431  27fb25aa-f148-423f-967c-4d1764e26b29      30/07/2022
437  f078102e-7e35-4371-b48e-2989ff4cec4f      29/12/2023
469  0aba7275-6bd4-404d-894a-cf695bcc2b67      04/03/2023
506  a42657eb-b99d-4b66-b0e7-96a9cd6def89      06/07/2022
531  34d137e4-b03b-4ad4-8fc4-b1d964d5cc26      12/07/2023
563  f39c8b1d-595a-4656-8108-25981bf3fa14      03/04/2023
606  64f3ee25-c285-41ee-92b6-f70b006554ae      12/06/2024
626  65520cc1-c798-4024-9caf-e1f893ef9cac      18/11/2022
668  952adac7-c15e-47f0-ad86-aeb2205bea77      01/01/2023
683  31d41f19-548d-48eb-bd31-513c084db798      05/06/2023
735  21e43f66-a2ee-4fbe-be6b-c9d1f4070402      13/10/2022
751  8ba90acb-a0a2-488e-bd60-677aec340cd6      20/09/2022
789  3292fdfd-806c-4226-bfed-4649f18ad018      05/07/2022
807  eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b      2023-03-23
868  87dd6224-a2fd-4d05-b79f-3f9f3354a5b6      19/11/2023
875  3227645b-d344-4a66-a17a-001d33bfdfa0      17/03/2023
879  181ad5a0-fb64-470c-9e97-5dbd7a938afc      01/08/2022
887  16ade59d-d408-4c0d-81b7-be87248ff74b      30/05/2023

In [65]:
# Convert the original date column to text first
date_text = transactions_clean["TransactionDate"].astype("string").str.strip()

# Try DD/MM/YYYY format
date_dmy = pd.to_datetime(
    date_text,
    format="%d/%m/%Y",
    errors="coerce"
)

# Try YYYY-MM-DD for anything that wasn't converted
date_ymd = pd.to_datetime(
    date_text,
    format="%Y-%m-%d",
    errors="coerce"
)

# Combine the two results
transactions_clean["TransactionDate"] = date_dmy.fillna(date_ymd)

In [66]:
transactions_clean["TransactionDate"].isna().sum()

98

In [67]:
transactions_clean["TransactionDate"].dtype

dtype('<M8[ns]')

In [68]:
transactions_clean[
    transactions_clean["TransactionDate"].isna()
][["TransactionID", "TransactionDate"]].head(10)

                            TransactionID TransactionDate
31   434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e             NaT
94   05d6d53f-92d1-4be7-9346-2d142470f849             NaT
106  22da76bb-b240-4e90-8efe-de5e07061c51             NaT
121  fb09f753-0b5d-4612-9d6a-3fe220f0f3aa             NaT
124  c5c4ab32-3a2a-4748-96b7-f5ebbba384f2             NaT
238  e3a950b7-a993-4b3e-ac84-20d3e292833a             NaT
252  04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3             NaT
258  81ecc5aa-a0e6-4aab-a600-cc7137bc16a1             NaT
356  ea7f4d30-45c8-4e24-8f37-c30527a1d6a3             NaT
389  a9272080-cc7f-4f82-9977-857549f2c895             NaT

In [69]:
bad_date_ids = transactions_clean.loc[
    transactions_clean["TransactionDate"].isna(),
    "TransactionID"
]

transactions[
    transactions["TransactionID"].isin(bad_date_ids)
][["TransactionID", "TransactionDate"]].head(10)

                            TransactionID TransactionDate
31   434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e      01/04/2024
94   05d6d53f-92d1-4be7-9346-2d142470f849      13/12/2022
106  22da76bb-b240-4e90-8efe-de5e07061c51      26/10/2022
121  fb09f753-0b5d-4612-9d6a-3fe220f0f3aa      25/02/2023
124  c5c4ab32-3a2a-4748-96b7-f5ebbba384f2      23/03/2023
238  e3a950b7-a993-4b3e-ac84-20d3e292833a      24/05/2023
252  04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3      16/09/2023
258  81ecc5aa-a0e6-4aab-a600-cc7137bc16a1      11/09/2023
283  7202af3a-448f-4970-9674-40f736cfdfde      2023-02-26
356  ea7f4d30-45c8-4e24-8f37-c30527a1d6a3      28/10/2022

In [70]:
def convert_date(x):
    if pd.isna(x):
        return pd.NaT
    
    x = str(x).strip()
    
    for fmt in ["%d/%m/%Y", "%Y-%m-%d"]:
        try:
            return pd.to_datetime(x, format=fmt)
        except ValueError:
            pass
    
    return pd.NaT


transactions_clean["TransactionDate"] = (
    transactions_clean["TransactionDate"].apply(convert_date)
)

In [71]:
transactions_clean["TransactionDate"].isna().sum()

3015

In [72]:
transactions_clean["TransactionDate"].isna().sum()

3015

In [73]:
transactions_clean["TransactionDate"].head(10)

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
5   NaT
6   NaT
7   NaT
8   NaT
9   NaT
Name: TransactionDate, dtype: datetime64[ns]

In [74]:
transactions_clean["TransactionDate"].isna().value_counts()

TransactionDate
True    3015
Name: count, dtype: int64

In [75]:
transactions_clean["TransactionDate"] = transactions_clean["TransactionID"].map(
    transactions.drop_duplicates("TransactionID").set_index("TransactionID")["TransactionDate"]
)

In [76]:
transactions_clean["TransactionDate"].head(10)

0    2024-05-15
1    2023-04-26
2    2022-09-23
3    2024-04-15
4    2024-06-03
5    2024-04-07
6    2024-01-12
7    2023-03-10
8    2024-01-26
9    2023-06-15
Name: TransactionDate, dtype: object

In [77]:
transactions_clean["TransactionDate"].isna().sum()

0

In [78]:
transactions_clean["TransactionDate"] = pd.to_datetime(
    transactions_clean["TransactionDate"],
    errors="coerce"
)

In [79]:
transactions_clean["TransactionDate"].dtype

dtype('<M8[ns]')

In [80]:
transactions_clean["TransactionDate"].isna().sum()

99

In [81]:
missing_date_ids = transactions_clean.loc[
    transactions_clean["TransactionDate"].isna(),
    "TransactionID"
]

In [82]:
transactions[
    transactions["TransactionID"].isin(missing_date_ids)
][["TransactionID", "TransactionDate"]]

                             TransactionID TransactionDate
31    434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e      01/04/2024
94    05d6d53f-92d1-4be7-9346-2d142470f849      13/12/2022
106   22da76bb-b240-4e90-8efe-de5e07061c51      26/10/2022
121   fb09f753-0b5d-4612-9d6a-3fe220f0f3aa      25/02/2023
124   c5c4ab32-3a2a-4748-96b7-f5ebbba384f2      23/03/2023
...                                    ...             ...
2954  353bce84-6f13-4cb4-9ef4-c287772674a8      30/05/2023
3038  27fb25aa-f148-423f-967c-4d1764e26b29      2024-04-18
3048  6c2c5c2b-7601-41dc-9f56-4009de6f3cea      2023-05-10
3094  62186b07-9cda-44c5-bf76-bdb0f97aaf39      2023-02-04
3113  f39c8b1d-595a-4656-8108-25981bf3fa14      2024-03-05

[99 rows x 2 columns]

In [83]:
transactions_clean["TransactionDate"] = transactions.loc[
    transactions_clean.index,
    "TransactionDate"
].values

In [84]:
transactions_clean["TransactionDate"] = pd.to_datetime(
    transactions_clean["TransactionDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [85]:
transactions_clean["TransactionDate"].isna().sum()

0

In [86]:
transactions_clean["TransactionDate"].dtype

dtype('<M8[ns]')

In [87]:
transactions_clean.shape

(3015, 7)

In [88]:
transactions_clean.duplicated().sum()

0

In [89]:
transactions_clean.isna().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             283
ProductCategory    282
PaymentMethod        0
Amount_Clean       313
dtype: int64

In [90]:
transactions_clean.dtypes

CustomerID                 object
TransactionID              object
TransactionDate    datetime64[ns]
Amount                     object
ProductCategory            object
PaymentMethod              object
Amount_Clean              float64
dtype: object

In [91]:
transactions_clean["CustomerID"].value_counts(dropna=False).head(20)

CustomerID
b03edff3-4a64-4e5e-8818-10e37291a8c6    6
e54d1219-b6b3-4b5c-8b75-62f4148c23b6    6
49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd    6
577fcc56-95dc-443a-9289-d12614f5cea3    6
79fc606a-c02c-4c39-b065-3e88a59b366c    5
71d8ab24-0827-437d-a3cb-0abf7a81061d    5
9b25a2c1-514e-425f-be87-a57533d5503e    5
4f6d0e26-dbf8-4abe-8b06-083acba71564    5
799943c7-3b71-4f24-9b16-c2fcaf9b3871    5
bf0ab935-f8a4-4d18-894c-bbd1d776a07d    5
c2c93273-8204-4385-8dd5-a277dc51989f    5
c6789ac7-81c7-469a-a613-fe1fe1487953    5
473f3b1f-2e0e-40a6-8917-b3aac5296a01    4
0064a8b2-71d3-41c1-a46a-6eea56fdff91    4
c71e53bd-d52e-43c7-853a-bde70ff3cf38    4
958e5c8d-48ca-42dd-bb71-a766a374233a    4
e556be3f-49dd-47c3-9bd1-6f2fb1b79d52    4
db10c135-1080-4fce-b653-d5a5fb572fa8    4
6e820fd4-83e9-41c3-8c2a-4c39b93d9a22    4
d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9    4
Name: count, dtype: int64

In [92]:
transactions_clean["TransactionID"].value_counts(dropna=False).head(20)

TransactionID
f39c8b1d-595a-4656-8108-25981bf3fa14    2
7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6    2
2e0b66a9-af5d-4cf9-bb60-55ab2932edee    2
5f93f1dc-0363-4e69-979b-f5d58fd42658    2
dc9453eb-3922-4a5f-91c0-ccb226ca91f7    2
022cfd97-a8e8-4e50-8700-2720d52bfd75    2
652636b6-5c72-44e1-aefb-6adce412ee75    2
62186b07-9cda-44c5-bf76-bdb0f97aaf39    2
6c2c5c2b-7601-41dc-9f56-4009de6f3cea    2
27fb25aa-f148-423f-967c-4d1764e26b29    2
eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b    2
5fca256b-cd5a-48fa-8b07-37f39adde8c9    2
185ee140-348a-4461-bd40-07a7e8535815    2
c751a808-ed8d-44d0-8c52-8253ad564c9a    2
7202af3a-448f-4970-9674-40f736cfdfde    2
80793666-f9f0-4bcb-9072-456ca4e6ab88    1
10a73856-a58e-4709-a641-dbc16a92d301    1
12d80278-2d5f-42f1-9bad-a693f60021ca    1
5f2c3722-0674-454b-bae5-034c3a1829f8    1
f34d7640-c48a-4610-93a2-650b4884fd1a    1
Name: count, dtype: int64

In [93]:
transactions_clean[
    transactions_clean["TransactionID"].duplicated(keep=False)
].sort_values("TransactionID")

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod,Amount_Clean
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal,586.87
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal,NaN
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal,0.00
413,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,953.86,Health & Beauty,PayPal,953.86
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card,-100.00
431,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2022-07-30,506.96,Automotive,Credit Card,506.96
2081,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,504.42,Electronics,Bank Transfer,504.42
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer,-100.00
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer,-100.00
220,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,125.77,NaN,Bank Transfer,125.77
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer,-100.00
1093,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,764.92,Clothing,Bank Transfer,764.92
2371,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,2023-04-05,NaN,Home & Garden,Bank Transfer,NaN
3094,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,2023-02-04,NaN,Home & Garden,Bank Transfer,NaN
629,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,0,Electronics,Debit Card,0.00
3153,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,974.25,Electronics,Debit Card,974.25
3048,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,2023-05-10,591.61,Clothing,Debit Card,591.61
2690,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,2024-06-10,591.61,Clothing,Debit Card,591.61
3105,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,2024-03-27,634.41,NaN,PayPal,634.41
283,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,2023-02-26,634.41,NaN,PayPal,634.41
940,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-14,272.68,Clothing,Debit Card,272.68
3164,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-20,272.68,Clothing,Debit Card,272.68
2610,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,766.97,Health & Beauty,Credit Card,766.97
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card,-100.00
1639,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,446.84,Health & Beauty,Debit Card,446.84
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card,-100.00
807,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,2023-03-23,50.07,Automotive,Bank Transfer,50.07
3157,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,2022-08-10,50.07,Automotive,Bank Transfer,50.07
3113,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,2024-03-05,252.7,Electronics,Debit Card,252.70
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,2023-04-03,-100,Electronics,Debit Card,-100.00

In [94]:
transactions_clean["ProductCategory"].value_counts(dropna=False)

ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      530
Health & Beauty    528
NaN                282
Name: count, dtype: int64

In [95]:
transactions_clean["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Debit Card       767
Credit Card      755
PayPal           750
Bank Transfer    743
Name: count, dtype: int64

In [96]:
transactions_clean[
    transactions_clean["Amount_Clean"] <= 0
][["TransactionID", "TransactionDate", "Amount", "Amount_Clean", "ProductCategory", "PaymentMethod"]]

,TransactionID,TransactionDate,Amount,Amount_Clean,ProductCategory,PaymentMethod
134,793af848-8138-40e7-929c-67254ea56ca7,2023-07-22,0,0.0,Home & Garden,PayPal
196,a6b7182d-6c74-4fa5-9491-035e49e5eb87,2023-11-09,0,0.0,Electronics,Bank Transfer
274,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,-100.0,NaN,PayPal
308,c0ea759c-a09f-4989-bc3b-f56a0c0400d8,2022-08-13,0,0.0,Home & Garden,PayPal
319,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100,-100.0,Health & Beauty,Debit Card
...,...,...,...,...,...,...
3050,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,-100.0,NaN,Bank Transfer
3073,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,-100.0,Electronics,Bank Transfer
3123,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,-100.0,Clothing,Bank Transfer
3174,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,0.0,Health & Beauty,PayPal
3177,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,-100.0,Health & Beauty,Credit Card

In [97]:
transactions_clean["Amount_Clean"].describe()

count    2702.000000
mean      489.788919
std       299.239453
min      -100.000000
25%       228.240000
50%       496.625000
75%       746.697500
max       999.860000
Name: Amount_Clean, dtype: float64

In [98]:
transactions_clean["Amount_Clean"].isna().sum()

313

In [99]:
print("Shape:", transactions_clean.shape)
print("Duplicate rows:", transactions_clean.duplicated().sum())

print("\nMissing values:")
print(transactions_clean.isna().sum())

print("\nData types:")
print(transactions_clean.dtypes)

Shape: (3015, 7)
Duplicate rows: 0

Missing values:
CustomerID           0
TransactionID        0
TransactionDate      0
Amount             283
ProductCategory    282
PaymentMethod        0
Amount_Clean       313
dtype: int64

Data types:
CustomerID                 object
TransactionID              object
TransactionDate    datetime64[ns]
Amount                     object
ProductCategory            object
PaymentMethod              object
Amount_Clean              float64
dtype: object

In [100]:
print("===== DATASET 1: CUSTOMER TRANSACTIONS =====")

print("\n1. DATASET SHAPE")
print(transactions_clean.shape)

print("\n2. COLUMN NAMES")
print(transactions_clean.columns.tolist())

print("\n3. DUPLICATE ROWS")
print(transactions_clean.duplicated().sum())

print("\n4. MISSING VALUES")
print(transactions_clean.isna().sum())

print("\n5. DATA TYPES")
print(transactions_clean.dtypes)

print("\n6. NUMERIC AMOUNT SUMMARY")
print(transactions_clean["Amount_Clean"].describe())

===== DATASET 1: CUSTOMER TRANSACTIONS =====

1. DATASET SHAPE
(3015, 7)

2. COLUMN NAMES
['CustomerID', 'TransactionID', 'TransactionDate', 'Amount', 'ProductCategory', 'PaymentMethod', 'Amount_Clean']

3. DUPLICATE ROWS
0

4. MISSING VALUES
CustomerID           0
TransactionID        0
TransactionDate      0
Amount             283
ProductCategory    282
PaymentMethod        0
Amount_Clean       313
dtype: int64

5. DATA TYPES
CustomerID                 object
TransactionID              object
TransactionDate    datetime64[ns]
Amount                     object
ProductCategory            object
PaymentMethod              object
Amount_Clean              float64
dtype: object

6. NUMERIC AMOUNT SUMMARY
count    2702.000000
mean      489.788919
std       299.239453
min      -100.000000
25%       228.240000
50%       496.625000
75%       746.697500
max       999.860000
Name: Amount_Clean, dtype: float64

Dataset 2 – Customer Demographics

In [101]:
import os
os.getcwd()

'/home/cbda0a06-4d87-42d7-846a-95a540b4f879'

In [102]:
import os
os.listdir()

['.pythonstartup.py',
 'MML Week 2 ',
 '.virtualenvs',
 '.profile',
 'anaconda_projects',
 '.ipython',
 '.ipynb_checkpoints',
 '.local',
 '.bashrc',
 '.gitconfig',
 '.anaconda',
 '.npm',
 '.vimrc',
 '.jupyter',
 '.conda']

In [103]:
demographics = pd.read_csv("MML Week 2 /customer_demographics_contaminated.csv")

In [104]:
demographics.shape

(3200, 6)

In [105]:
demographics.head()

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24

In [106]:
demographics.columns.tolist()

['CustomerID', 'Age', 'Gender', 'Location', 'IncomeLevel', 'SignupDate']

In [107]:
demographics.duplicated().sum()

177

In [108]:
demographics[demographics.duplicated(keep=False)].sort_values("CustomerID").head(20)

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
3039,0047d8ce-a5bb-4db7-860f-6ff66e1cd060,40.0,Male,Mitchellview,Medium,2021-11-11
2559,0047d8ce-a5bb-4db7-860f-6ff66e1cd060,40.0,Male,Mitchellview,Medium,2021-11-11
1511,05609335-a647-4691-80a8-82b43518b767,52.0,Male,Jonesside,Low,2023-10-07
3169,05609335-a647-4691-80a8-82b43518b767,52.0,Male,Jonesside,Low,2023-10-07
1105,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
3061,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
2409,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09
3199,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09
3088,09c0c7b1-2af9-4485-a602-d49c6cdcf2d0,31.0,Female,New Patricktown,Low,2023-06-20
886,09c0c7b1-2af9-4485-a602-d49c6cdcf2d0,31.0,Female,New Patricktown,Low,2023-06-20
3107,0ab0e741-f4ad-4d82-92c4-b5055b5c5549,26.0,Male,South Robertberg,NaN,2019-07-14
2906,0ab0e741-f4ad-4d82-92c4-b5055b5c5549,26.0,Male,South Robertberg,NaN,2019-07-14
1318,0b5275cc-0b6c-4451-ac40-469e74c35f00,33.0,Female,Port Aliceton,High,2024-05-09
3001,0b5275cc-0b6c-4451-ac40-469e74c35f00,33.0,Female,Port Aliceton,High,2024-05-09
2075,0b78455d-7ecd-41c3-953b-4c883ce336f1,26.0,Male,Lake Crystal,Medium,2022-09-11
3109,0b78455d-7ecd-41c3-953b-4c883ce336f1,26.0,Male,Lake Crystal,Medium,2022-09-11
1693,0c68dabb-b818-43bf-96de-e0b384ace943,54.0,Male,North Samuelborough,High,2024-01-08
3125,0c68dabb-b818-43bf-96de-e0b384ace943,54.0,Male,North Samuelborough,High,2024-01-08
3056,0d1d1b53-3a9d-4be9-9857-371dc98aba1e,57.0,Female,New Tylerfurt,Low,2024-06-12
381,0d1d1b53-3a9d-4be9-9857-371dc98aba1e,57.0,Female,New Tylerfurt,Low,2024-06-12

In [109]:
demographics_clean = demographics.drop_duplicates().copy()

In [110]:
demographics_clean.shape

(3023, 6)

In [111]:
demographics_clean.isna().sum()

CustomerID       0
Age            276
Gender           0
Location         0
IncomeLevel    285
SignupDate       0
dtype: int64

In [112]:
demographics_clean["Age"].describe()

count     2747
unique      58
top       62.0
freq        70
Name: Age, dtype: object

In [113]:
demographics_clean["Age"].value_counts(dropna=False).sort_index()

Age
-1          28
-1.0         2
150         31
150.0        2
18.0        55
19.0        48
20.0        48
21.0        45
22.0        38
23.0        52
24.0        36
25.0        55
26.0        64
27.0        54
28.0        50
29.0        41
30.0        43
31.0        46
32.0        43
33.0        34
34.0        64
35.0        39
36.0        55
37.0        54
38.0        51
39.0        46
40.0        49
41.0        43
42.0        49
43.0        56
44.0        37
45.0        54
46.0        50
47.0        45
48.0        48
49.0        50
50.0        41
51.0        48
52.0        54
53.0        53
54.0        43
55.0        58
56.0        51
57.0        67
58.0        53
59.0        54
60.0        47
61.0        56
62.0        70
63.0        49
64.0        52
65.0        47
66.0        50
67.0        49
68.0        62
69.0        48
70.0        56
Unknown     34
NaN        276
Name: count, dtype: int64

In [114]:
demographics_clean[
    demographics_clean["Age"].isin(["Unknown", -1, "-1", -1.0, 150, "150", 150.0])
][["CustomerID", "Age", "Gender", "Location", "IncomeLevel", "SignupDate"]]

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
10,c96a5ee9-f1a6-416a-adc6-1c8b128c7399,150,Male,Hansontown,High,2020-09-17
48,b1d6a46b-214c-4592-9688-82d0fd977bb2,150,Female,North Cindyhaven,Low,2020-06-28
64,52303d17-9d24-4c20-89e3-7bcfa92140c9,150,Male,Spencermouth,NaN,2022-06-25
72,7a461a97-18fd-4686-ab3f-adaded72069d,150,Male,Pageside,High,2024-04-16
85,9bd23b55-cbc0-4082-ae18-916ea8895c07,Unknown,Male,Kimberlyview,Low,2024-01-26
...,...,...,...,...,...,...
2975,ba3f79ad-b3ab-47e5-8803-22cb4ea8cf13,150,Female,Rodriguezside,NaN,2022-08-10
3004,3814b8e4-cade-4665-86af-dda3e3628f17,150,Female,Port Bonnieshire,Medium,2021-06-25
3132,6b2f8f03-ab9e-48a6-a07e-10e794b04fe0,-1,Male,Lake Karen,Low,2023-04-04
3138,7544489f-ec7e-48af-bec6-b6eab94a6e5c,150,Male,South Jared,High,2024-03-02
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,Unknown,Male,Gregoryfurt,High,2020-06-23

In [115]:
demographics_clean["Age"] = pd.to_numeric(
    demographics_clean["Age"].replace(["Unknown", -1, -1.0, 150, 150.0], pd.NA),
    errors="coerce"
)

In [116]:
demographics_clean["Age"].value_counts(dropna=False).sort_index()

Age
-1.0       30
 18.0      55
 19.0      48
 20.0      48
 21.0      45
 22.0      38
 23.0      52
 24.0      36
 25.0      55
 26.0      64
 27.0      54
 28.0      50
 29.0      41
 30.0      43
 31.0      46
 32.0      43
 33.0      34
 34.0      64
 35.0      39
 36.0      55
 37.0      54
 38.0      51
 39.0      46
 40.0      49
 41.0      43
 42.0      49
 43.0      56
 44.0      37
 45.0      54
 46.0      50
 47.0      45
 48.0      48
 49.0      50
 50.0      41
 51.0      48
 52.0      54
 53.0      53
 54.0      43
 55.0      58
 56.0      51
 57.0      67
 58.0      53
 59.0      54
 60.0      47
 61.0      56
 62.0      70
 63.0      49
 64.0      52
 65.0      47
 66.0      50
 67.0      49
 68.0      62
 69.0      48
 70.0      56
 150.0     33
 NaN      310
Name: count, dtype: int64

In [117]:
demographics_clean["IncomeLevel"].value_counts(dropna=False)

IncomeLevel
High      946
Low       923
Medium    869
NaN       285
Name: count, dtype: int64

In [118]:
demographics_clean["Gender"].value_counts(dropna=False)

Gender
Female    1528
Male      1495
Name: count, dtype: int64

In [119]:
demographics_clean["Location"].nunique(), demographics_clean["Location"].isna().sum()

(2696, 0)

In [120]:
demographics_clean["Location"].value_counts().head(15)

Location
Port Michael         5
Michaelville         4
Port Eric            4
Michaelton           4
West David           4
West Michael         4
New Michael          4
West Robert          4
North Jennifer       4
Brownland            3
North Christopher    3
Port William         3
Brownbury            3
Kimberlyview         3
East Brittany        3
Name: count, dtype: int64

In [121]:
demographics_clean["SignupDate"].dtype

dtype('O')

In [122]:
demographics_clean["SignupDate"].value_counts(dropna=False).head(10)

SignupDate
2024-06-08    9
2020-11-09    8
2020-07-21    6
2022-02-24    6
2021-11-11    6
2023-09-24    6
2021-11-02    6
2022-12-10    6
2021-03-29    6
2020-06-23    6
Name: count, dtype: int64

In [123]:
demographics_clean["SignupDate"] = pd.to_datetime(
    demographics_clean["SignupDate"],
    errors="coerce"
)

In [124]:
demographics_clean["SignupDate"].dtype

dtype('<M8[ns]')

In [125]:
demographics_clean["CustomerID"].dtype, demographics_clean["CustomerID"].isna().sum()

(dtype('O'), 0)

In [126]:
print("===== DATASET 2: CUSTOMER DEMOGRAPHICS =====")

print("\n1. DATASET SHAPE")
print(demographics_clean.shape)

print("\n2. COLUMN NAMES")
print(demographics_clean.columns.tolist())

print("\n3. DUPLICATE ROWS")
print(demographics_clean.duplicated().sum())

print("\n4. MISSING VALUES")
print(demographics_clean.isna().sum())

print("\n5. DATA TYPES")
print(demographics_clean.dtypes)

===== DATASET 2: CUSTOMER DEMOGRAPHICS =====

1. DATASET SHAPE
(3023, 6)

2. COLUMN NAMES
['CustomerID', 'Age', 'Gender', 'Location', 'IncomeLevel', 'SignupDate']

3. DUPLICATE ROWS
0

4. MISSING VALUES
CustomerID       0
Age            310
Gender           0
Location         0
IncomeLevel    285
SignupDate      98
dtype: int64

5. DATA TYPES
CustomerID             object
Age                   float64
Gender                 object
Location               object
IncomeLevel            object
SignupDate     datetime64[ns]
dtype: object

In [127]:
demographics_clean[demographics_clean["SignupDate"].isna()][
    ["CustomerID", "SignupDate"]
].head(20)

                               CustomerID SignupDate
27   23b3aa96-cec0-4964-8176-98ce984158a8        NaT
96   cc5da89b-c295-41c3-b27d-c759cca78ba8        NaT
127  febc5ef6-d9f5-459d-b7ef-40fdb9c2588b        NaT
158  ae075979-b98f-46bf-bd3b-cc75f7216c3c        NaT
160  bbf7c36f-3745-4d3a-9e33-f927c2755f65        NaT
183  1eea3d52-fd1a-403e-8e70-7919dca848ee        NaT
225  b72f2a59-aab0-447d-bb31-9bdc1405cc72        NaT
250  e5d3b19d-e899-4694-aac3-705696a235e3        NaT
292  7c40da22-ee52-4381-b501-c5fc91248472        NaT
348  8880506d-dbb6-42ea-98c3-c0b7454c04bb        NaT
352  9f6b9ab6-1055-4a20-912e-23adb444695c        NaT
436  f9edc899-39cf-4227-9b37-c40003bc28af        NaT
438  c82f4cc5-e3e9-4919-ad14-bc9ad485fd45        NaT
440  46c6bd4d-5902-44cc-b3b2-fb82f6ab2cb6        NaT
446  9aa1e60e-df4c-4987-9ee8-70b4e6edbca6        NaT
470  1d4e578b-738c-4913-84f4-b008488eab48        NaT
502  f2fa85fd-89ce-488e-bbdf-4535ae78da25        NaT
523  e4ce98e6-81ec-48c3-a198-813996dfdf1b        NaT
572  9107778f-48e1-4ecd-9511-10e549305477        NaT
594  5a8b6207-27b9-4ad1-9157-cfac7d2abd4d        NaT

In [128]:
demographics.loc[
    demographics_clean[demographics_clean["SignupDate"].isna()].index,
    "SignupDate"
].head(20)

27     30/01/2020
96     12/01/2024
127    10/01/2022
158    14/01/2024
160    07/07/2019
183    25/11/2020
225    10/06/2024
250    18/03/2021
292    27/06/2023
348    24/04/2020
352    03/04/2020
436    04/02/2024
438    22/04/2023
440    06/06/2020
446    16/02/2023
470    11/09/2020
502    20/05/2021
523    12/11/2019
572    26/10/2021
594    08/10/2022
Name: SignupDate, dtype: object

In [129]:
demographics_clean["SignupDate"] = demographics.loc[
    demographics_clean.index, "SignupDate"
]

demographics_clean["SignupDate"] = pd.to_datetime(
    demographics_clean["SignupDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [130]:
demographics_clean["SignupDate"].isna().sum()

0

In [131]:
print("===== DATASET 2: CUSTOMER DEMOGRAPHICS =====")

print("\n1. DATASET SHAPE")
print(demographics_clean.shape)

print("\n2. COLUMN NAMES")
print(demographics_clean.columns.tolist())

print("\n3. DUPLICATE ROWS")
print(demographics_clean.duplicated().sum())

print("\n4. MISSING VALUES")
print(demographics_clean.isna().sum())

print("\n5. DATA TYPES")
print(demographics_clean.dtypes)

===== DATASET 2: CUSTOMER DEMOGRAPHICS =====

1. DATASET SHAPE
(3023, 6)

2. COLUMN NAMES
['CustomerID', 'Age', 'Gender', 'Location', 'IncomeLevel', 'SignupDate']

3. DUPLICATE ROWS
0

4. MISSING VALUES
CustomerID       0
Age            310
Gender           0
Location         0
IncomeLevel    285
SignupDate       0
dtype: int64

5. DATA TYPES
CustomerID             object
Age                   float64
Gender                 object
Location               object
IncomeLevel            object
SignupDate     datetime64[ns]
dtype: object

Dataset 3 – Social Media Interactions

In [132]:
social = pd.read_csv("MML Week 2 /social_media_interactions_contaminated.csv")

In [133]:
social.shape

(3200, 6)

In [134]:
social.columns.tolist()

['CustomerID',
 'InteractionID',
 'InteractionDate',
 'Platform',
 'InteractionType',
 'Sentiment']

In [135]:
social.head()

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN

In [136]:
social.duplicated().sum()

180

In [137]:
social[social.duplicated(keep=False)].sort_values("CustomerID").head(20)

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
3192,00c15eff-8bcf-4d12-a5d4-992e45e3309f,b1f6f6bd-d15d-4c44-87af-5485f68eda24,2024-05-19,Instagram,Comment,Positive
2949,00c15eff-8bcf-4d12-a5d4-992e45e3309f,b1f6f6bd-d15d-4c44-87af-5485f68eda24,2024-05-19,Instagram,Comment,Positive
890,03d6d674-5310-4a05-ab0b-8cfedc46a1ab,bfaa9449-7975-4a58-8aa0-aeed770f11ea,2024-03-09,Twitter,Share,Negative
3191,03d6d674-5310-4a05-ab0b-8cfedc46a1ab,bfaa9449-7975-4a58-8aa0-aeed770f11ea,2024-03-09,Twitter,Share,Negative
1073,03d7aa25-0f9d-40a3-9eb4-baa5a4e14e9f,af09d9d2-4f96-49f9-91c4-ca9695d26bc5,2023-09-18,NaN,Comment,Positive
3092,03d7aa25-0f9d-40a3-9eb4-baa5a4e14e9f,af09d9d2-4f96-49f9-91c4-ca9695d26bc5,2023-09-18,NaN,Comment,Positive
1478,05e09646-040f-425a-b5b3-d6f113e0c75b,1a0f939f-9fa0-4e37-802b-b81cf41cee2e,2024-02-24,Facebook,Like,Positive
3168,05e09646-040f-425a-b5b3-d6f113e0c75b,1a0f939f-9fa0-4e37-802b-b81cf41cee2e,2024-02-24,Facebook,Like,Positive
3063,060cfd42-8d99-4264-aa27-e8d0b537e207,bd403c39-df73-44fc-82f6-b458dc0e44e4,2023-12-27,Twitter,Comment,Positive
2095,060cfd42-8d99-4264-aa27-e8d0b537e207,bd403c39-df73-44fc-82f6-b458dc0e44e4,2023-12-27,Twitter,Comment,Positive
3029,0a3c84ac-0979-470f-83b6-adb135f223c4,fc3894d4-1d48-442d-8000-edbfaf49864d,2023-09-01,Instagram,Like,Positive
2107,0a3c84ac-0979-470f-83b6-adb135f223c4,fc3894d4-1d48-442d-8000-edbfaf49864d,2023-09-01,Instagram,Like,Positive
3118,0c298fc3-6e30-4478-bc30-f1b56b2e655d,020837db-5783-4ac9-9955-1ace5175a1a0,2023-07-05,Facebook,Share,Positive
1051,0c298fc3-6e30-4478-bc30-f1b56b2e655d,020837db-5783-4ac9-9955-1ace5175a1a0,2023-07-05,Facebook,Share,Positive
3121,0dd7e84b-0aa4-4883-8bda-447e31b595d5,f6c2eff0-c39c-40e0-979c-3ff2267795c3,2024-05-30,Twitter,Comment,Positive
1723,0dd7e84b-0aa4-4883-8bda-447e31b595d5,f6c2eff0-c39c-40e0-979c-3ff2267795c3,2024-05-30,Twitter,Comment,Positive
3038,104bf67f-1567-4f5e-b41b-64b230b1e898,9c6600a4-4127-4ddb-ac37-bfb8ffb42bdc,2023-09-15,Twitter,Comment,Neutral
2650,104bf67f-1567-4f5e-b41b-64b230b1e898,9c6600a4-4127-4ddb-ac37-bfb8ffb42bdc,2023-09-15,Twitter,Comment,Neutral
280,12dc6fed-c847-4040-93a1-dd00eb7ccbc0,9c56ffce-209f-48fc-b3ac-1c3840c83029,2023-09-18,Facebook,Share,Negative
3154,12dc6fed-c847-4040-93a1-dd00eb7ccbc0,9c56ffce-209f-48fc-b3ac-1c3840c83029,2023-09-18,Facebook,Share,Negative

In [138]:
social_clean = social.drop_duplicates().copy()

In [139]:
social_clean.shape

(3020, 6)

In [140]:
social_clean.isna().sum()

CustomerID           0
InteractionID        0
InteractionDate      0
Platform           291
InteractionType      0
Sentiment          309
dtype: int64

In [141]:
social_clean["Platform"].value_counts(dropna=False)

Platform
Instagram    921
Twitter      917
Facebook     891
NaN          291
Name: count, dtype: int64

In [142]:
social_clean["InteractionType"].value_counts(dropna=False)

InteractionType
Comment    1018
Share      1007
Like        995
Name: count, dtype: int64

In [143]:
social_clean["Sentiment"].value_counts(dropna=False)

Sentiment
Positive         905
Neutral          874
Negative         866
NaN              309
Very Negative     34
Very Positive     32
Name: count, dtype: int64

In [144]:
social_clean[social_clean["Sentiment"].isin(["Very Positive", "Very Negative"])].head(20)

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
44,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Very Negative
178,9e85fb2e-f7af-4338-9b2e-0b900102405c,83700ae7-6b30-4953-92d7-8897e1cc3c6f,2023-09-19,Twitter,Share,Very Positive
215,ed5dc22d-7406-40bf-a647-e880e75bdbdd,63ef7c3a-f3c3-4be3-ae83-df1189269fb5,2024-06-10,Instagram,Share,Very Positive
223,59e1ccfe-8f67-4f2c-8e4c-f1483df35ae8,b386be23-0455-4bda-a834-8b8cec80b5c8,2024-02-13,NaN,Share,Very Positive
240,d06373dd-8d92-4e7d-8329-c4ce400b0d42,297c9a08-b7bf-4514-834e-b1bc756157de,2024-05-29,Twitter,Share,Very Negative
398,b8749ac7-628a-4fc6-81f4-8fd885fcca3c,6d5c56db-47ee-4dfc-87ce-8efca4285fe0,2024-02-14,Instagram,Share,Very Positive
401,7f237eb5-f4a7-403f-a3cc-72748ee810c6,28fe15c0-ab85-45ff-b00f-647460eb07f0,2024-06-23,NaN,Comment,Very Negative
410,7689da74-95f4-4977-a528-968d6e64235c,dc9d6c78-8772-44ed-8a7a-48e2eb968040,2023-11-14,NaN,Like,Very Positive
430,409c8d3d-63e6-4280-a699-91933c1eee73,dcecd08b-e5d5-4fae-a6a8-d04f478e5ce9,2024-03-03,Facebook,Like,Very Positive
431,710f0b73-da83-47ed-80a1-4a46a836eb67,48b04d2b-c534-4403-b5f3-60104ede1df2,2023-09-07,Twitter,Like,Very Positive
479,841fd92c-2c00-4beb-b870-76df175c4398,d2a7870b-9720-4ab2-99fb-f89fe6ce7b75,2023-09-03,Facebook,Share,Very Negative
556,31a64c59-e32d-4d9c-ba9c-f308acd78daf,baf88c76-d6b8-4a0c-be12-9dca9397a4d5,2024-02-24,Instagram,Share,Very Positive
557,094ee9c9-a553-4e24-b3a0-643ceff051fd,62e41731-5adb-40d9-beaa-649b4554321c,2024-03-30,Twitter,Comment,Very Positive
569,81be7ae8-5f41-4ee9-895e-b001c5c63186,d7211ae0-3a0a-4414-8f1f-8b6e860e25d2,2023-11-22,Instagram,Like,Very Positive
606,d91e9fd4-1922-4b2c-b958-0401ebbc6e48,2b0a4f94-e591-4ee0-acd1-60cd29d374e1,2023-08-13,Twitter,Comment,Very Negative
622,c3a5e86e-a74b-420e-b1e7-13bcbe6b71ac,8c1da393-7ea5-4405-b8c5-49953f75079a,2023-07-01,Instagram,Share,Very Positive
646,dd68aaa6-d50a-4b2f-be13-0331ceae7708,090130db-7bf3-4dd0-b530-b1082de20e3e,2024-01-22,NaN,Comment,Very Negative
670,41846ddf-f6d1-40ef-952b-652f8904d6ee,e96235c1-c42a-4f29-aabf-ea8709c14f07,2023-09-30,Twitter,Comment,Very Positive
744,be10f9ef-a8e8-4ee2-a296-48c31c209b14,b9dc5dbd-8c2a-42f3-9615-c5911fc93da0,2023-07-02,Instagram,Like,Very Positive
801,9eb78179-6de7-4c67-b04b-709c40f5ce01,f41e5d51-6f10-4dd1-81e9-d2b532a57a3f,2023-08-13,Instagram,Comment,Very Negative

In [145]:
social_clean["InteractionDate"].dtype

dtype('O')

In [146]:
social_clean["InteractionDate"].value_counts(dropna=False).head(15)

InteractionDate
2023-07-02    16
2024-01-30    15
2023-12-27    15
2024-06-29    15
2023-09-15    15
2023-12-02    15
2023-11-30    14
2024-02-12    14
2024-02-16    14
2024-02-26    14
2024-01-13    13
2024-04-04    13
2024-02-07    13
2024-03-15    13
2023-07-26    13
Name: count, dtype: int64

In [147]:
social_clean["InteractionDate"] = pd.to_datetime(
    social_clean["InteractionDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [148]:
social_clean["InteractionDate"].isna().sum()

0

In [149]:
print("CustomerID:", social_clean["CustomerID"].dtype, social_clean["CustomerID"].isna().sum())
print("InteractionID:", social_clean["InteractionID"].dtype, social_clean["InteractionID"].isna().sum())

CustomerID: object 0
InteractionID: object 0

In [150]:
print("===== DATASET 3: SOCIAL MEDIA INTERACTIONS =====")

print("\n1. DATASET SHAPE")
print(social_clean.shape)

print("\n2. COLUMN NAMES")
print(social_clean.columns.tolist())

print("\n3. DUPLICATE ROWS")
print(social_clean.duplicated().sum())

print("\n4. MISSING VALUES")
print(social_clean.isna().sum())

print("\n5. DATA TYPES")
print(social_clean.dtypes)

===== DATASET 3: SOCIAL MEDIA INTERACTIONS =====

1. DATASET SHAPE
(3020, 6)

2. COLUMN NAMES
['CustomerID', 'InteractionID', 'InteractionDate', 'Platform', 'InteractionType', 'Sentiment']

3. DUPLICATE ROWS
0

4. MISSING VALUES
CustomerID           0
InteractionID        0
InteractionDate      0
Platform           291
InteractionType      0
Sentiment          309
dtype: int64

5. DATA TYPES
CustomerID                 object
InteractionID              object
InteractionDate    datetime64[ns]
Platform                   object
InteractionType            object
Sentiment                  object
dtype: object

In [151]:
import os
print(os.getcwd())

/home/cbda0a06-4d87-42d7-846a-95a540b4f879

In [152]:
import os
print(os.listdir())

['.pythonstartup.py', 'MML Week 2 ', '.virtualenvs', '.profile', 'anaconda_projects', '.ipython', '.ipynb_checkpoints', '.local', '.bashrc', '.gitconfig', '.anaconda', '.npm', '.vimrc', '.jupyter', '.conda']

In [153]:
import os
print(os.listdir("MML Week 2 "))

['.ipynb_checkpoints', 'customer_transactions_contaminated.csv', 'Data Cleaning and Preprocessing.ipynb', 'social_media_interactions_contaminated.csv', 'customer_demographics_contaminated.csv']